my_site/blogapp/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter

app_name = 'blog'

urlpatterns = [
    path('', BasedView.as_view(), name='blog'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('articles/latest/feed/', LatestArticlesFeed(), name='article_latest_feed'),
]

my_site/my_auth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import *

app_name ='my_auth'

urlpatterns = [

    path('login/', LoginView.as_view(
        template_name='my_auth/login.html',
        redirect_authenticated_user=True),
        name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),

    path('about/', AboutMyView.as_view(), name='about'),
    path('about/<int:pk>/', DetailUserView.as_view(), name='user_detail'),
    path('about/<int:pk>/update/', UpdateProfile.as_view(), name='user_update'),
    path('about/list/', UserListView.as_view(), name='user_list'),
    path('register/', RegisterUserView.as_view(), name='register'),

    path('cookie/get/', get_cookie_view, name='cookie_get'),
    path('cookie/set/', set_cookie_view, name='cookie_set'),
    path('session/get/', get_session_view, name='session_get'),
    path('session/set/', set_session_view, name='session_set'),

    path('foo-bar/', FooBarView.as_view(), name='foo_bar'),

    path('hello/', HelloView.as_view(), name='hello'),

    ]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path('api/', include('my_api_app.urls')),
    path('req/', include('requestdataapp.urls')),
    path('sitemap/', include('sitemap.urls')),
    path('blog/', include('blogapp.urls')),
    path('sitemap.xml',
         sitemap,
         {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('my_auth.urls')),
    path('shop/', include('shop_app.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

my_site/my_auth/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

def user_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return 'users/user_{pk}/avatar/{filename}'.format(
        pk=instance.user.pk,
        filename=filename,
    )


class Profile(models.Model):

    class Meta:

        verbose_name = _("profile")
        verbose_name_plural = _("profiles")

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    bio = models.TextField(max_length=500, blank=True, verbose_name='Биография')
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, upload_to=user_avatar_directory_path, verbose_name='Изображение')

my_site/my_auth/forms.py
from django import forms
from .models import *





class AddAvatarForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = '__all__'



    avatar = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
    )

my_site/my_auth/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView
from django.utils.translation import gettext_lazy as _, ngettext


from .models import *
from .forms import *

class AboutMyView(TemplateView):
    template_name = 'my_auth/about_me.html'


class UserListView(ListView):
    template_name = 'my_auth/user_list.html'
    queryset = User.objects.all()
    context_object_name = 'Users'


class DetailUserView(DetailView):
    template_name = 'my_auth/user_detail.html'
    context_object_name = 'Profile'
    queryset = Profile.objects.all()


class UpdateProfile(UserPassesTestMixin, UpdateView):

    def test_func(self):
        return self.request.user.is_staff or self.request.user.is_superuser or \
               self.request.user.id == self.get_object().user_id

    model = Profile
    form_class = AddAvatarForm
    #fields = 'bio', 'avatar'
    template_name = 'my_auth/user_update_form.html'
    template_name_suffix = '_update_form'


    def get_success_url(self):
        return reverse('my_auth:user_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        return super().form_valid(form)




class RegisterUserView(CreateView):
    form_class = UserCreationForm
    template_name = 'my_auth/register.html'
    success_url = reverse_lazy('my_auth:about')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return response




class MyLogoutView(LogoutView):
    next_page = reverse_lazy('my_auth:login')

@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('ASSSSSS', 'QWERTY', max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('ASSSSSS', 'default value')
    return HttpResponse(f'Куки значение: {value!r}')


@permission_required('my_auth.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['footbar'] = 'Что то записали и получили'
    return HttpResponse('Установка сессии!')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('footbar', 'default')
    return HttpResponse(f'Значение сессии: {value!r}')


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'spam': 'eggs'})



class HelloView(View):
    welcome = _('Welcome hello world!')
    def get(self, request: HttpRequest):
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_lines = ngettext(
            'one products',
            '{count} products',
            items,
        )
        products_line = products_lines.format(count=items)

        return HttpResponse(f'\n<h2>{self.welcome}</h2>\n\n<h3>{products_line}</h3>')

my_site/my_auth/templates/my_auth/about_me.html
{% extends 'my_auth/basa.html' %}

{% block title %}
    About_my
{% endblock %}

{% block body %}
    <h2>Информация обо мне:</h2>
    {% if user.is_authenticated %}
        <h3>Детали:</h3>
        <div>Пользователь: {{ user.username }}</div>
        <div>Аватарка:</div>

            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
            {% else %}
            <div>Нет аваторки</div>
            {% endif %}

        <div>Имя: {{ user.first_name }}</div>
        <div>Фамилия: {{ user.last_name }}</div>
        <div>Email: {{ user.email }}</div>
        <div>Bio: {{ user.profile.bio }}</div>


    {% else %}
        <h3>Пользователь не авторизован</h3>
    {% endif %}
    <p><a href="{% url 'my_auth:user_list' %}">Список всех пользователей</a></p>

{% endblock %}

my_site/my_auth/templates/my_auth/basa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
        {% block body %}

        {% endblock %}
</body>
</html>

my_site/my_auth/templates/my_auth/login.html
{% extends 'my_auth/basa.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form   method="post">
    {% csrf_token %}
   {{ form.as_p }}
    <button type="submit">Login</button>
    </form>
{% endblock %}}

my_site/my_auth/templates/my_auth/register.html
{% extends 'my_auth/basa.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block body %}
    <h2>Регистрация</h2>

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Регистрация">
    </form>
{% endblock %}

my_site/my_auth/templates/my_auth/user_detail.html
{% extends 'my_auth/basa.html' %}

{% block title %}
    About_Profile
{% endblock %}

{% block body %}
    <h2>Информация о пользователе:</h2>

        <h3>Детали:</h3>
        <div>Пользователь: {{ Profile.user.username}}</div>
        <div>Аватарка:</div>

            {% if Profile.avatar %}
                <img src="{{ Profile.avatar.url }}" alt="{{ Profile.avatar.name }}">
            {% else %}
            <div>Нет аваторки</div>
            {% endif %}
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Загрузить</button>
        </form>

        <div>Имя: {{ Profile.user.first_name }}</div>
        <div>Фамилия: {{ Profile.user.last_name }}</div>
        <div>Email: {{ Profile.user.email }}</div>
        <div>Bio: {{ Profile.bio }}</div>

    {% if perms.my_auth.change_profile %}
        <p><a href="{% url 'my_auth:user_update' pk=Profile.id %}">Обновить информацию</a></p>
    {% endif %}
    <p><a href="{% url 'my_auth:user_list' %}">Список всех пользователей</a></p>

{% endblock %}

my_site/my_auth/templates/my_auth/user_list.html
{% extends 'my_auth/basa.html' %}

{% block title %}
    UserList
{% endblock %}

{% block body %}
    <h3>Список пользователей:</h3>
    {% if Users %}
    <div>
    {%for user in Users %}
        <a href="{% url 'my_auth:user_detail' pk=user.profile.pk %}">Пользователь: {{ user.username }}</a>

{#        <div>Аватарка:</div>#}
{#        {% if user.profile.avatar %}#}
{#            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">#}
{#        {% else %}#}
{#            <div>Нет аваторки</div>#}
{#        {% endif %}#}
    <div>Имя: {{ user.first_name }}</div>
    <div>Фамилия: {{ user.last_name }}</div>
    <div>Email: {{ user.email }}</div>
    <div>Bio: {{ user.profile.bio }}</div>

    </div>
    <p></p>
        {% endfor %}
    {% endif %}
{% endblock %}

my_site/my_auth/templates/my_auth/user_update_form.html
{% extends 'my_auth/basa.html' %}

{% block title %}
    UpdateProfile
{% endblock %}

{% block body %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
    </form>

    <p><a href="{% url 'my_auth:about' %}">Информация о пользователе</a></p>

{% endblock %}