my_site/blogapp/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter

app_name = 'blog'

urlpatterns = [
    path('', BasedView.as_view(), name='blog'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('articles/latest/feed/', LatestArticlesFeed(), name='article_latest_feed'),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path('api/', include('my_api_app.urls')),
    path('req/', include('requestdataapp.urls')),
    path('sitemap/', include('sitemap.urls')),
    path('blog/', include('blogapp.urls')),
    path('sitemap.xml',
         sitemap,
         {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('my_auth.urls')),
    path('shop/', include('shop_app.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

my_site/shop_app/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter



routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)



app_name ='shop_app'
urlpatterns = [
    path('', ShopInfo.as_view(), name='shop'),
    path('api/', include(routers.urls)),

    path('products/', ProductListView.as_view(), name='products_list'),
    path('products/<int:pk>/', ProductDetails.as_view(), name='products_details'),
    path('products/<int:pk>/update', ProductUpdate.as_view(), name='product_update'),
    path('products/<int:pk>/delete', ProductDell.as_view(), name='product_delete'),
    path('products/create/', ProductCreate.as_view(), name='create_product'),
    path('products/export/', ProductsDataExportView.as_view(), name='products_export'),
    path('products/latest/feed/', LatestProductsFeed(), name='products_latest_feed'),

    path('order/', OrderList.as_view(), name='order_list'),
    path('order/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('order/<int:pk>/update', OrderUpdate.as_view(), name='order_updates'),
    path('order/<int:pk>/delete', OrderDelete.as_view(), name='order_delete'),
    path('order/create/', CreateOrder.as_view(), name='create_order'),
    path('order/export/', OrderDataExportView.as_view(), name='orders_export'),

    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user_orders'),
    path('users/<int:user_id>/orders/export/', UserOrdersExportView.as_view(), name='user_orders_export'),
]

my_site/shop_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):


    class Meta:
        ordering = ['name', 'price']
        verbose_name = _("product")
        verbose_name_plural = _("products")


    name = models.CharField(max_length=50, verbose_name='Название продукта', db_index=True)
    description = models.TextField(null=False, blank=True, verbose_name='Описание продукта', db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Цена', db_index=True)
    discount = models.PositiveSmallIntegerField(default=0, verbose_name='Скидка', db_index=True)
    created_in = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', db_index=True)
    archived = models.BooleanField(default=False, verbose_name='Архивировано', db_index=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Создатель', db_index=True)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def get_absolute_url(self):
        return reverse('shop_app:products_details', args=[str(self.pk)])




    def __str__(self) -> str:
        return f'Продукт ({self.name!r})'


def product_images_directory_path(instance: 'ProductImage', filename: str) -> str:
    return 'products/product_{pk}/images/{filename}'.format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    discription_image = models.CharField(max_length=150, null=False, blank=True, verbose_name='Описание к картинке')




class Order(models.Model):

    class Meta:
        verbose_name = _("order")
        verbose_name_plural = _("orders")

    delivery_address = models.TextField(null=False, blank=True, verbose_name='Адрес доставки')
    promocode = models.CharField(max_length=20, null=False, blank=True, verbose_name='Промокод')
    created_in = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Заказчик')
    products = models.ManyToManyField(Product, related_name='orders', verbose_name='Продукты')
    receipt = models.FileField(null=True, upload_to='order/receipts/', verbose_name='Чек')

    def get_absolute_url(self):
        return reverse('shop_app:order_detail', args=[str(self.pk)])

my_site/shop_app/forms.py
from _ast import pattern

from django import forms
from django.core import validators
from.models import *



class AddProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'discount', 'preview']


    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
    )


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = '__all__'



class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

my_site/shop_app/views.py
from django.contrib.auth.decorators import permission_required, login_required

import logging
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.syndication.views import Feed
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, redirect, reverse, get_object_or_404, reverse
from timeit import default_timer
from django.urls import reverse_lazy

from csv import DictWriter

from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.views import APIView

from .common import save_csv_products
from .forms import *
from .models import *

from rest_framework.viewsets import ModelViewSet
from rest_framework.request import Request
from rest_framework.response import Response
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.parsers import MultiPartParser
from django_filters.rest_framework import DjangoFilterBackend

from rest_framework.decorators import action

from django.core.cache import cache

log = logging.getLogger(__name__)


@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all().order_by('pk')
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,

        OrderingFilter,
    ]
    search_fields = [
        'name',
        'description',
    ]

    ordering_fields = [
        'pk',
        'price',
        'name',
    ]

    @extend_schema(
        summary='GET one product by ID',
        description='Retrieves product? returns 404 is not found',
        responses={
            200: ProductSerializer,
            400: OpenApiResponse(description='Empty response, product by id not found')
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=['get'], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')
        filename = 'product-export.csv'
        response['Content-Disposition'] = f'attachment; filename={filename}'
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'name',
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response

    @action(
        detail=False,
        methods=['post'],
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES['file'].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)



class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all().order_by('pk')
    serializer_class = OrderSerializer
    filter_backends = [

        DjangoFilterBackend,
        OrderingFilter,
    ]

    filterset_fields = [
        'user',
        'delivery_address',
        'promocode',
        'products',
    ]

    ordering_fields = [
        'pk',
        'created_in',
    ]




class ShopInfo(View):
    def get(self, request):
        products = Product.objects.all()
        context = {
            'items': 1,
        }
        log.debug('Products for shop index: %s', products)
        log.info('Rendering shop index')
        return render(request, 'shop_app/shopping.html', context=context)


# Класс просмотра списка продуктов
class ProductListView(ListView):
    template_name = 'shop_app/products_list.html'
    #    model = Product
    queryset = Product.objects.filter(archived=False)
    context_object_name = 'Products'


# Класс просмотра информации о продукте
class ProductDetails(DetailView):
    template_name = 'shop_app/product_details.html'
    # model = Product
    queryset = Product.objects.filter(archived=False).prefetch_related('images')
    context_object_name = 'Products'


# Класс создания продукта
class ProductCreate(PermissionRequiredMixin, CreateView):
    model = Product
    permission_required = 'shop_app.add_product'
    # form_class = AddProductForm
    fields = 'name', 'price', 'description', 'discount', 'preview'
    success_url = reverse_lazy('shop_app:products_list')

    #
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


# Класс обновления продукта
class ProductUpdate(UserPassesTestMixin, UpdateView):

    def test_func(self):
        return self.request.user.is_superuser or \
               self.request.user.id == self.get_object().created_by.id


    model = Product
    #fields = 'name', 'price', 'description', 'discount', 'preview'
    template_name_suffix = '_update_form'
    form_class = AddProductForm

    def get_success_url(self):
        return reverse(
            'shop_app:products_details',
            kwargs={'pk': self.object.pk},
        )

    def form_valid(self, form):
        response = super(ProductUpdate, self).form_valid(form)

        for image in form.files.getlist('images'):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )

        return response



class ProductDell(UserPassesTestMixin, DeleteView):
    def test_func(self):
        return self.request.user.id == self.get_object().created_by.id

    model = Product
    success_url = reverse_lazy('shop_app:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)



class LatestProductsFeed(Feed):
    title = 'Shop Products (latest)'
    description = 'Updates on changes and addition shop products'
    link = reverse_lazy('shop_app:articles')

    def items(self):
        return (
        Product.objects.order_by('-created_in')[:3]
        )

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]


class CreateOrder(LoginRequiredMixin, CreateView):
    model = Order
    fields = 'user', 'delivery_address', 'products', 'promocode'
    success_url = reverse_lazy('shop_app:order_list')


class OrderList(LoginRequiredMixin, ListView):
    queryset = Order.objects.select_related('user').prefetch_related('products')
    context_object_name = 'Orders'


class OrderDetail(PermissionRequiredMixin, DetailView):
    permission_required = 'shop_app.view_order'
    queryset = Order.objects.select_related('user').prefetch_related('products')


class OrderUpdate(UpdateView):
    model = Order
    fields = 'user', 'delivery_address', 'promocode', 'products'
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse(
            'shop_app:order_detail',
            kwargs={'pk': self.object.pk},
        )


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('shop_app:order_list')


class ProductsDataExportView(View):
    def get(self, request):
        products = Product.objects.order_by('pk').all()
        products_data = [
            {'pk': product.pk,
             'name': product.name,
             'price': product.price,
             'archived': product.archived,
             }
            for product in products
        ]
        mame = Product.objects.all()
        print(mame)
        return JsonResponse({'products': products_data})


class OrderDataExportView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request):
        orders = Order.objects.order_by('pk').all()
        orders_data = [
            {'pk': order.pk,

             'promocode': order.promocode,
             'delivery_address': order.delivery_address,
             'products': [{
                 'name': product.name,
                }
                for product in order.products.all()
                ]
             }
            for order in orders
        ]
        return JsonResponse({'orders': orders_data})


class UserOrdersListView(ListView):

    template_name = 'shop_app/user_orders.html'
    context_object_name = 'user_orders'

    def get_queryset(self, **kwargs):
        self.owner = get_object_or_404(User, pk=self.kwargs['user_id'])
        return Order.objects.filter(user=self.owner).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner
        return context


class UserOrdersExportView(View):

    # def get_queryset(self, **kwargs):
    #
    #     return Order.objects.filter(user=self.owner)

    def get(self, request, *args, **kwargs):
        owner = get_object_or_404(User, pk=self.kwargs['user_id'])
        cache_key = 'user_orders_data_export_' + str(self.kwargs['user_id'])
        user_orders_data = cache.get(cache_key)
        if user_orders_data is None:
            orders = Order.objects.filter(user=owner).all().order_by('pk')
            print(orders)
            user_orders_data = OrderSerializer(orders, many=True)
            cache.set(cache_key, user_orders_data, 30)
        return JsonResponse({'user_orders': user_orders_data.data})

my_site/shop_app/templates/shop_app/basa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Basa shopp
        {% endblock %}
    </title>
</head>

<body>
    {% block  body %}
    <h1>Тут что то будет</h1>
    {% endblock %}
</body>

<div>
    Время: {% now "H:i "%}
</div>

<div>
    Дата: {% now "d.m.Y"%}
</div>

</html>

my_site/shop_app/templates/shop_app/create-product.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h2>{{ title }}</h2>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Создать
            </button>
        </form>
    </div>
    <div>
    <p><a href="{% url 'shop_app:product_update' %}">Перейти на страницу с продуктами</a></p>


    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/create_order.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h2>{{ title }}</h2>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Создать
            </button>
        </form>
    </div>
    <div>
    <a href="{% url 'shop_app:order_list' %}">Обновить заказ</a>
    </div>
    <div>
    <a href="{% url 'shop_app:order_list' %}">Перейти на страницу с заказами</a>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/order_confirm_delete.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    Удаление заказа
{% endblock %}

{% block body %}
    <h2>Уверены ли вы что хотите удалить заказ {{ object.pk }}?</h2>
    <br>
    <div>
        <a href="{% url 'shop_app:order_detail' pk=object.pk %}">Вернуться к заказу № {{ object.pk }}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Удалить</button>
            <p></p>
        </form>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/order_detail.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    Заказ № {{ object.pk }}
{% endblock %}

{% block body %}
    <h2>Заказ № {{ object.pk }}:</h2>

    <div>
        <div>Заказал: {% firstof object.user.first_name order.user.username %}</div>
            <div>Промокод: {{ object.promocode }}</div>
            <div>Адрес доставки: {{ object.delivery_address }}</div>
            <div>
            <p>
                Продукты заказа:
                <ul>
                    {% for product in object.products.all %}
                        <li>
                        {{ product.name }} по {{ product.price }} рублей.
                        </li>
                    {% endfor %}
                </ul>
            </p>
            </div>
   </div>

    <div>
    <a href="{% url 'shop_app:order_list' %}">Возврат к списку заказов</a>
    </div>
    <div>
    <a href="{% url 'shop_app:order_updates' pk=object.pk %}">Обновление текущего заказа</a>
    </div>
    <div>
    <a href="{% url 'shop_app:order_delete' pk=object.pk %}">Удаление текущего заказа</a>
    </div>
    <p></p>


{% endblock %}

my_site/shop_app/templates/shop_app/order_list.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    Список заказов
{% endblock %}

{% block body %}
    <h2>Список заказов:</h2>
    {% if Orders %}
        <div>
            {% for order in Orders %}
                <p><a href="{% url 'shop_app:order_detail' pk=order.pk %}">Заказ № {{ order.pk }}</a></p>
                <div>Заказал:
                    <a href="{% url 'shop_app:user_orders' user_id=order.user_id %}">{% firstof order.user.first_name order.user.username %}</a>
                </div>
                <div>Промокод: {{ order.promocode }}</div>
                <div>Адрес доставки: {{ order.delivery_address }}</div>
                <div>
                    Продукты заказа:
                    <ul>
                        {% for product in order.products.all %}
                            <li>
                                {{ product.name }} по {{ product.price }} рублей.
                            </li>

                        {% endfor %}

                </ul>
            </div>
            <p></p>

        {% endfor %}


        </div>
    {% else %}
        <h2>Нет заказов</h2>

    {% endif %}

     <p><a href="{% url 'shop_app:create_order' %}">Создать заказ</a></p>


{% endblock %}

my_site/shop_app/templates/shop_app/order_update.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    Обновление заказа №{{ object.pk }}
{% endblock %}

{% block body %}
    <h2>Обновление заказа №{{ object.pk }}</h2>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Обновить</button>
        </form>


    <p><a href="{% url 'shop_app:order_list' %}">Вернуться к списку заказов</a></p>

    </div>

{% endblock %}

my_site/shop_app/templates/shop_app/product_confirm_delete.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    Архив продукта
{% endblock %}

{% block body %}
    <h2>Уверены ли вы что хотите поместить в архив {{ object.name }}?</h2>
    <br>
    <div>
        <a href="{% url 'shop_app:products_details' pk=object.pk %}">Вернуться к продукту № {{ object.pk }}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">В архив</button>
            <p></p>
        </form>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/product_details.html
{% extends 'shop_app/basa.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Product' %}№{{ Products.pk}}
{% endblock %}

{% block body %}
    <h2>{% translate 'Product' %}<strong>{{ Products.name }}</strong></h2>
    <div>
        <div>{% translate 'Description' %}:<em>{{ Products.description }}</em></div>
        <div>{% translate 'Price' %}: {{ Products.price }}</div>
        <div>{% translate 'Discount' %}: {{ Products.discount }}</div>
        <div>{% translate 'Created_by' %}: {{ Products.created_by }}</div>
            {% if Products.preview %}
                <img src="{{ Products.preview.url }}" alt="{{ products.preview.name }}">
            {% endif %}
        <p>{% translate 'Archived' %}: {{ Products.archived }}</p>


        <h2>{% translate 'Images' %}:</h2>

            <p>
            {% blocktranslate count count_images=Products.images.all|length %}
                There is one image
            {% plural %}
                There are {{ count_images }} images
            {% endblocktranslate %}
            </p>

            {% for imag in Products.images.all %}
                <div>
                    <img src="{{ imag.image.url }}" alt="{{ imag.image.name }}">
                    <div>
                        {{  imag.discription_image }}
                    </div>
                </div>
            {% empty %}
            <div>{% translate 'No images' %}</div>
            {% endfor %}
        <p></p>

    </div>
    <div>
        {% url 'shop_app:products_list' as list_product_url %}
        {% blocktranslate %}
            <a href={{ list_product_url }}>Back list products</a>
        {% endblocktranslate %}
    </div>
    {% if perms.shop_app.change_product %}
    <div>
        {% url 'shop_app:product_update' pk=Products.pk as update_product_url %}
        {% blocktranslate %}
            <a href={{ update_product_url }}>Update product</a>
        {% endblocktranslate %}
    </div>
    {% endif %}
    {% if perms.shop_app.delete_product %}
    <div>
        {% url 'shop_app:product_delete' pk=Products.pk as archive_product_url %}
        {% blocktranslate %}
            <a href={{ archive_product_url }}>Add a product to the archive</a>
        {% endblocktranslate %}

    </div>
    {% endif %}


    <p></p>
{% endblock %}

my_site/shop_app/templates/shop_app/product_form.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    Создание продукта
{% endblock %}

{% block body %}
    <h2>Создание продукта</h2>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Создать</button>
        </form>
    </div>
    <div>
    <p>
        <a href="{% url 'shop_app:products_list' %}">К списку продуктов</a>
    </p>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/product_update_form.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    Обновление продукта
{% endblock %}

{% block body %}
    <h2>Обновление продукта</h2>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Обновить
            </button>
        </form>
    </div>
    <div>
    <p>
    <button><a href="{% url 'shop_app:products_details' pk=object.pk %}">Перейти к продукту № {{ object.pk }}</a></button>
    </p>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

my_site/shop_app/templates/shop_app/products_list.html
{% extends 'shop_app/basa.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h3>{% translate 'Product' %}:</h3>
    {% if Products %}
        <p>
            {% blocktranslate count count_products=Products.all|length %}
                There is only one product
                {% plural %}
                There are {{ count_products }} products
            {% endblocktranslate %}
        </p>
        <div>
            {% for product in Products %}
                {% if perms.shop_app.view_product %}
                    <lu><b><a href="{% url 'shop_app:products_details' pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{ product.name }}</a></b></lu>
                {% else %}
                    <lu><b>{% translate 'Name' context 'product name' %}: {{ product.name }}</b></lu>
                {% endif %}

                <div>{% translate 'Price' %}: {{ product.price }}</div>

                {% translate 'no discount' as no_discount %}
                <div>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</div>

                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}

                <p></p>
                <hr>

            {% endfor %}

        </div>

        <div>
        {% if perms.shop_app.add_product %}
        <a href="{% url 'shop_app:create_product' %}">{% translate 'Create new product' %}</a>
        </div>
        {% endif %}
        <p></p>
    {% else %}
        {% url 'shop_app:create_product' as create_product_url %}
        {% blocktranslate %}
            <h3>No products</h3>
            <a href={{ create_product_url }}>Create a new one</a>
        {% endblocktranslate %}

    <p></p>
    {% endif %}
{% endblock %}

my_site/shop_app/templates/shop_app/shopping.html
{% extends 'shop_app/basa.html' %}

{% block title %}
    SHOP
{% endblock %}


{% block body %}

    <h2>Возможные действия:</h2>
    <h3>Вы можете посмотреть список продуктов (добавив products/)</h3>
    <h3>Вы можете посмотреть список заказов (добавив order/)</h3>

    <p>
    <strong>
        You have {{ items }} item{{ items|pluralize }}
    </strong>
    </p>
{% endblock %}